a=int(input('month: '))
if a==1: print('january - 31 days')
elif a==2: print('febuary - 28 or 29 days')
elif a==3:print('march - 31 days')
elif a==4:print('april - 30 days')
elif a==5:print('may - 31 days')
elif a==6:print('june - 30 days')
elif a==7:print('july - 31 days')
elif a==8:print('August - 31 days')
elif a==9:print('september - 30 days')
elif a==10:print('october - 31 days')
elif a==11:print('november - 30 days')
elif a==12:print('december - 31 days')